/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package theknife.gui;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.border.Border;
import theknife.obj.review.Response;

/**
 * The {@code ResponseGUI} class is a panel for displaying a {@link Response}.
 * <p>
 * This class is part of the GUI layer of the {@link ReviewGUI} and it is typically used for displaying a {@code Response}.
 * </p>
 * 
 * @author Damiano De Mutiis    761348 (CO)
 * @author Matteo Porto Bonacci 761396 (CO)
 * @author Matteo Monticone     761701 (CO)
 * @author Mattia Tamburo       760743 (CO)
 */
public final class ResponseGUI extends javax.swing.JPanel 
{

    //<editor-fold defaultstate="collapsed" desc="Constructor">
    /**
     * Creates a new {@code ResponseGUI} panel and initializes its components.
     * <p>
     * This constructor also sets the {@link Response} used to display it. 
     * </p>
     * @param response - the {@link Response} object used to display
     * @param bg - the {@code Color} of the background of the {@code ResponseGUI}
     */
    public ResponseGUI(Response response, Color bg) {
        initComponents();
        this.response = response;
        this.bg = bg;
        initGUI();
    }
    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc="Initialization">
    /**
     * Initializes the graphical user interface (GUI) for the {@code ResponseGUI} page.
     */
    private void initGUI()
    {
        initFields();
        initResponseGUI();
    }
    
    /**
     * Initializes the basic fields of the {@code ResponseGUI} panel.
     */
    private void initFields() {
        lbl_username    = new JLabel(response.getUsername());
        txt_content     = new JTextArea(response.getContent());
        scrlPnl_content = new JScrollPane(txt_content, JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED, JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
    }
    
    /**
     * Initializes the layout and appearance of the home page.
     */
    private void initResponseGUI() {
        this.setLayout(new BorderLayout());
        this.setBackground(bg);
        this.setPreferredSize(new Dimension(0, USERNAME_HEIGHT + CONTENT_HEIGHT));
        
        lbl_username.setBackground         (this.getBackground());
        lbl_username.setForeground         (FG_DEFAULT);
        lbl_username.setHorizontalAlignment(JLabel.LEFT);
        lbl_username.setVerticalAlignment  (JLabel.CENTER);
        lbl_username.setFont               (this.getFont());
        lbl_username.setBorder             (PADDING_LBL);
        lbl_username.setOpaque             (true);
        lbl_username.setPreferredSize(new Dimension(0, USERNAME_HEIGHT));
        
        txt_content.setBackground   (this.getBackground());
        txt_content.setBorder       (PADDING_TXT);
        txt_content.setFont         (new Font(this.getFont().getFontName(), this.getFont().getStyle(), 22));
        txt_content.setLineWrap     (true);
        txt_content.setWrapStyleWord(true);
        
        scrlPnl_content.setBackground                 (this.getBackground());
        scrlPnl_content.setBorder                     (BORDER_PNL);
        scrlPnl_content.getVerticalScrollBar()  .setUI(new CustomJScrollBar());
        scrlPnl_content.getHorizontalScrollBar().setUI(new CustomJScrollBar());
        
        this.add(lbl_username, BorderLayout.NORTH);
        this.add(txt_content,  BorderLayout.CENTER);
    }
    //</editor-fold>
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    //<editor-fold defaultstate="collapsed" desc="Consts">
    private final Color  FG_DEFAULT      = Color.BLACK;
    private final Border PADDING_LBL     = BorderFactory.createEmptyBorder(0, 5, 0, 5);
    private final Border PADDING_TXT     = BorderFactory.createEmptyBorder(3, 3, 3, 3);
    private final Border BORDER_PNL      = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.BLACK);
    private final int    USERNAME_HEIGHT = 30;
    private final int    CONTENT_HEIGHT  = 150;
    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc="Components">
    private JScrollPane scrlPnl_content;
    private JLabel lbl_username;
    private JTextArea txt_content;
    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc="Fields">
    private final Response response;
    private final Color    bg;
    //</editor-fold>
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
