package theknife.gui;

import java.awt.BorderLayout;

/**
 * The Home class represents the home screen of the application.
 * <p>
 * It contains a list of restaurants found by typing on the {@code Upperbar} {@link JTextField}.<br>
 * The components are arranged in a {@link BorderLayout} and properly styled.<br>
 * This class handles events such as button clicks and text input to interact with the rest of the application.
 * </p>
 * 
 * @author Matteo Monticone     761701 (CO)
 * @author Damiano De Mutiis    ------ (CO)
 * @author Matteo Porto Bonacci ------ (CO)
 * @author Mattia Tamburo       ------ (CO)
 */
public final class Home extends javax.swing.JPanel {

    /**
     * Creates a new {@code Home} panel and initializes its components.
     * <p>
     * This constructor also sets the main panel to control the screen transitions using {@link PanelMain#showCard}.
     * </p>
     * 
     * @param main the main panel that manages the screen layout
     */
    public Home(PanelMain main) {
        initComponents();
        pnl_main = main;
        initGUI();
    }
    
    /**
     * Initializes the graphical user interface (GUI) for the home page.
     */
    private void initGUI() {
        initFields();
        initHome();
    }
    
    /**
     * Initializes all the fields in the home.
     */
    private void initFields() {
        
    }
    
    /**
     * Initializes the layout and appearance of the home page.
     */
    private void initHome() {
        this.setLayout(new BorderLayout());
        this.add(new Upperbar(pnl_main), BorderLayout.NORTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    //<editor-fold defaultstate="collapsed" desc="Components">
    private final PanelMain pnl_main;
    //</editor-fold>
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
