package theknife.gui;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JLabel;

/**
 * @author Matteo Monticone     761701 (CO)
 * @author Damiano De Mutiis    ------ (CO)
 * @author Matteo Porto Bonacci ------ (CO)
 * @author Mattia Tamburo       ------ (CO)
 */

public class Login extends javax.swing.JPanel {

    /**
     * Creates new form Login
     * @param main
     */
    public Login(PanelMain main) {
        initComponents();
        initGUI();
        pnl_main = main;
    }
    
    private void initGUI() {
        initFields();
        initLoginGUI();
        initEvents();
    }
    
    private void initFields() {
        this.setLayout(new BorderLayout());
        btn_home = new JLabel("Example");
    }
    
    private void initLoginGUI() {
        btn_home.setPreferredSize(new Dimension(this.getWidth(), 100));
        btn_home.setBackground(Color.GREEN);
        btn_home.setOpaque(true);
        this.add(btn_home, BorderLayout.SOUTH);
    }
    
    private void initEvents() {
        btn_home.addMouseListener(new java.awt.event.MouseAdapter(){
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_home_MouseClicked(evt);
            }
        });
    }
    
    private void btn_home_MouseClicked(java.awt.event.MouseEvent evt) {
        pnl_main.showCard("home");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private PanelMain pnl_main;
    private JLabel btn_home;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
