package theknife.gui;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.ComponentEvent;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.border.Border;
import theknife.obj.review.Review;

/**
 * The {@code PreviewReviewGUI} class represents a graphical panel component for displaying a single {@link Review} object.
 * <p>
 * This class is part of the GUI layer of the {@link RestaurantGUI} and is typically used to have a graphical interface of the review itself.
 * </p>
 * 
 * @author Damiano De Mutiis    761348 (CO)
 * @author Matteo Porto Bonacci 761396 (CO)
 * @author Matteo Monticone     761701 (CO)
 * @author Mattia Tamburo       761743 (CO)
 */
public final class PreviewReviewGUI extends javax.swing.JPanel {
    
    //<editor-fold defaultstate="collapsed" desc="Constructor">
    /**
     * Creates a new {@code PreviewReviewGUI} panel and initializes its components.
     * <p>
     * This constructor also sets the review to insert the data needed to have a preview of the review itself.
     * </p>
     *
     * @param review the {@link Review} class that represents the review
     * @param bg the {@code Color} of the background for the {@code PreviewReviewGUI}
     */
    public PreviewReviewGUI(Review review, Color bg) {
        initComponents();
        this.bg     = bg;
        this.review = review;
        initGUI();
    }
    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc="Initialization">
    /**
     * Initializes the graphical user interface (GUI) for the {@code PreviewReviewGUI} page.
     */
    private void initGUI() {
        initFields();
        initPreviewReviewGUI();
        initEvents();
    }
    
    /**
     * Initializes the basic fields of the {@code PreviewReviewGUI} panel.
     */
    private void initFields() 
    {
        pnl_usernameRating = new JPanel(new BorderLayout());
        lbl_username       = new JLabel(review.getUsername());
        lbl_rating         = new JLabel(String.valueOf(review.getRating()));
        txt_content        = new JTextArea(review.getContent().length() > MAX_CONTENT_LENGTH ? review.getContent().substring(0, MAX_CONTENT_LENGTH) + "..." : review.getContent());
        lbls               = new JLabel[] {
            lbl_username,
            lbl_rating
        };
    }
    
    /**
     * Initializes the layout and appearance of the home page.
     */
    private void initPreviewReviewGUI() 
    {
        this.setBackground(bg);
        this.setLayout(new BorderLayout());
        this.setPreferredSize(new Dimension(0, HEIGHT));
        
        pnl_usernameRating.setBackground(bg);
        pnl_usernameRating.setBorder(BORDER_NORTH_PNL);
        pnl_usernameRating.setPreferredSize(new Dimension(0, NORTH_CONTENT_HEIGHT));
        
        for (JLabel lbl : lbls) {
            lbl.setBackground(bg);
            lbl.setForeground(FG_DEFAULT);
            lbl.setHorizontalAlignment  (JLabel.LEFT);
            lbl.setVerticalAlignment    (JLabel.CENTER);
            lbl.setFont                 (this.getFont());
            lbl.setBorder               (PADDING_LBL);
            lbl.setOpaque               (true);
        }
        lbl_rating.setHorizontalAlignment(JLabel.RIGHT);
        
        txt_content.setBackground   (bg);
        txt_content.setBorder       (PADDING_TXT);
        txt_content.setLineWrap     (true);
        txt_content.setWrapStyleWord(true);
        txt_content.setEditable     (false);
        txt_content.setFocusable    (false);
        
        pnl_usernameRating.add(lbl_username, BorderLayout.CENTER);
        pnl_usernameRating.add(lbl_rating,   BorderLayout.EAST);
        
        this.add(pnl_usernameRating, BorderLayout.NORTH);
        this.add(txt_content,        BorderLayout.CENTER);
    }
    
    /**
     * Sets up event listeners for user interaction.
     */
    private void initEvents() 
    {
        
    }
    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc="Event Listeners">
    //</editor-fold>
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    //<editor-fold defaultstate="collapsed" desc="Consts">
    private final Color              FG_DEFAULT           = Color.BLACK;
    private final Border             PADDING_LBL          = BorderFactory.createEmptyBorder(5, 5, 5, 5);
    private final Border             PADDING_TXT          = BorderFactory.createEmptyBorder(3, 3, 3, 3);
    private final Border             BORDER_NORTH_PNL     = BorderFactory.createLineBorder(Color.BLACK, 1);
    private final int                NORTH_CONTENT_HEIGHT = 30;
    private final int                MAX_CONTENT_LENGTH   = 200;
    private final int                HEIGHT               = 100;
    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc="Components">
    private JPanel    pnl_usernameRating;
    private JLabel    lbl_username;
    private JLabel    lbl_rating;
    private JTextArea txt_content;
    private JLabel[]  lbls;
    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc="Fields">
    private final Color  bg;
    private final Review review;
    //</editor-fold>
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
