/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package theknife.gui;

import java.awt.Color;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.border.Border;
import theknife.obj.restaurant.Restaurant;

/**
 *
 * @author Matteo Monticone
 */
public class PreviewRestaurant extends javax.swing.JPanel {

    //<editor-fold defaultstate="collapsed" desc="Constructor">
    /**
     * Creates a new {@code PreviewRestaurant} panel and initializes its components.
     * <p>
     * This constructor also sets the restaurant to insert the data needed to have a preview of the restaurant itself.
     * </p>
     *
     * @param restaurant the {@link Restaurant} to set for the GUI preview
     */
    public PreviewRestaurant(Restaurant restaurant) {
        initComponents();
        this.restaurant = restaurant;
        initFields();
        initPreviewRestaurant();
        initEvents();
    }
    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc="Initialization">
    
    /**
     * Initializes the basic fields of the {@code PreviewRestaurant} panel.
     */
    private void initFields() {
        lbl_name      = new JLabel(restaurant.getName());
        lbl_address   = new JLabel(restaurant.getAddress());
        lbl_rating    = new JLabel(String.valueOf(restaurant.getRating()));
        lbl_award     = new JLabel(restaurant.getAward());
        lbl_greenStar = new JLabel(restaurant.isGreenStar() ? GREENSTAR_TRUE : GREENSTAR_FALSE);
        lbl_details   = new JLabel(DETAILS);
        lbls          = new JLabel[] {
            lbl_name,
            lbl_address,
            lbl_rating,
            lbl_award,
            lbl_greenStar,
            lbl_details
        };
    }
    
    /**
     * Initializes the layout and appearance of the home page.
     */
    private void initPreviewRestaurant() {
        this.setLayout(new GridBagLayout());
        
        for (int i = 0; i < lbls.length; i++) {
            lbls[i].setBackground(BG_DEFAULT);
            lbls[i].setForeground(FG_DEFAULT);
            lbls[i].setHorizontalAlignment(JLabel.CENTER);
            lbls[i].setVerticalAlignment  (JLabel.CENTER);
            lbls[i].setFont(new Font(this.getFont().getFontName(), this.getFont().getStyle(), 24));
            lbls[i].setOpaque(true);
        }
        
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridx      = 0;
        gbc.gridy      = 0;
        gbc.ipadx      = 10;
        gbc.ipady      = 10;
        gbc.gridwidth  = 1;
        gbc.gridheight = 2;
        gbc.weighty    = 1;
        gbc.insets     = INSETS;
        gbc.fill       = GridBagConstraints.BOTH;
        this.add(lbl_name, gbc);
        
        gbc.gridx++;
        gbc.gridwidth++;
        gbc.gridheight--;
        this.add(lbl_address, gbc);
        
        gbc.gridy++;
        this.add(lbl_rating, gbc);
        
        gbc.gridy++;
        gbc.gridx--;
        gbc.gridwidth--;
        this.add(lbl_details, gbc);
        
        gbc.gridx++;
        this.add(lbl_award, gbc);
        
        gbc.gridx++;
        this.add(lbl_greenStar, gbc);
    }
    
    /**
     * Sets up event listeners for user interaction.
     */
    private void initEvents() {
        
    }
    //</editor-fold>

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(15, 166, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    //<editor-fold defaultstate="collapsed" desc="Consts">
    private final Color    BG_DEFAULT         = new Color(65, 150, 79);
    private final Color    FG_DEFAULT         = new Color(47, 235, 78);
    private final Insets   INSETS             = new Insets(5, 5, 5, 5);
    private final String   DETAILS            = "Go to details";
    private final String   GREENSTAR_TRUE     = "Eco sustainable";
    private final String   GREENSTAR_FALSE    = "Not Eco sustainable";
    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc="Components">
    private JLabel   lbl_name;
    private JLabel   lbl_address;
    private JLabel   lbl_rating;
    private JLabel   lbl_award;
    private JLabel   lbl_greenStar;
    private JLabel   lbl_details;
    private JLabel[] lbls;
    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc="Fields">
    private final Restaurant restaurant;
    //</editor-fold>
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
