/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package theknife.gui;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Insets;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import theknife.Controller;
import theknife.obj.restaurant.Restaurant;

/**
 *
 * @author Matteo Monticone
 */
public class RestaurantGUI extends javax.swing.JPanel {

    //<editor-fold defaultstate="collapsed" desc="Constructor">
    /**
     * Creates a new {@code RestaurantGUI} panel and initializes its components.
     * <p>
     * This constructor also sets the restaurant to insert the data needed to have a preview of the restaurant itself.
     * </p>
     *
     * @param controller the {@link Controller} class that manages the screen layout
     * @param restaurant the {@link Restaurant} to set for the {@code RestaurantGUI}
     */
    public RestaurantGUI(Controller controller, Restaurant restaurant) {
        initComponents();
        this.controller = controller;
        this.restaurant = restaurant;
        initGUI();
    }
    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc="Initialization">
    /**
     * Initializes the graphical user interface (GUI) for the {@code PreviewRestaurant} page.
     */
    private void initGUI() {
        initFields();
        initPreviewRestaurant();
        initEvents();
    }
    
    /**
     * Initializes the basic fields of the {@code PreviewRestaurant} panel.
     */
    private void initFields() {
        lbl_name      = new JLabel(restaurant.getName());
        lbl_price     = new JLabel(String.valueOf(restaurant.getPrice()));
        lbl_currency  = new JLabel(restaurant.getCurrency());
        lbl_phoneNo   = new JLabel(restaurant.getPhoneNumber());
        lbl_country   = new JLabel(restaurant.getCountry());
        lbl_city      = new JLabel(restaurant.getCity());
        lbl_address   = new JLabel(restaurant.getAddress());
        lbl_latitude  = new JLabel(String.valueOf(restaurant.getLatitude()));
        lbl_longitude = new JLabel(String.valueOf(restaurant.getLongitude()));
        lbl_url       = new JLabel(restaurant.getUrl());
        lbl_webUrl    = new JLabel(restaurant.getWebsiteUrl());
        lbl_award     = new JLabel(restaurant.getAward());
        lbl_greenStar = new JLabel(restaurant.isGreenStar() ? GREENSTAR_TRUE : GREENSTAR_FALSE);
        lbl_services  = new JLabel(restaurant.getServicesAvailable());
        lbl_rating    = new JLabel(String.valueOf(restaurant.getRating()));
    }
    
    /**
     * Initializes the layout and appearance of the home page.
     */
    private void initPreviewRestaurant() {
        this.setLayout(new BorderLayout());
    }
    /**
     * Sets up event listeners for user interaction.
     */
    private void initEvents() {
        
    }
    //</editor-fold>
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(53, 216, 58));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    //<editor-fold defaultstate="collapsed" desc="Consts">
    private final Color    BG_DEFAULT         = new Color(65, 150, 79);
    private final Color    FG_DEFAULT         = new Color(47, 235, 78);
    private final Insets   INSETS             = new Insets(5, 5, 5, 5);
    private final String   GREENSTAR_TRUE     = "Eco sustainable";
    private final String   GREENSTAR_FALSE    = "Not Eco sustainable";
    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc="Components">
    private JPanel      pnl_restaurant;
    private JPanel      pnl_content;
    private JPanel      pnl_firstHalfContent;
    private JPanel      pnl_secondHalfcontent;
    private JScrollPane scrlPnl_description;
    private JScrollPane scrlPnl_reviews;
    private JTextArea   txt_description;
    private JLabel      lbl_name;
    private JLabel      lbl_price;
    private JLabel      lbl_currency;
    private JLabel      lbl_phoneNo;
    private JLabel      lbl_country;
    private JLabel      lbl_city;
    private JLabel      lbl_address;
    private JLabel      lbl_latitude;
    private JLabel      lbl_longitude;
    private JLabel      lbl_url;
    private JLabel      lbl_webUrl;
    private JLabel      lbl_award;
    private JLabel      lbl_greenStar;
    private JLabel      lbl_services;
    private JLabel      lbl_rating;
    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc="Fields">
    private final Controller controller;
    private final Restaurant restaurant;
    //</editor-fold>
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
