package theknife.gui;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.border.Border;
import theknife.Controller;
import theknife.obj.review.Review;

/**
 * The {@code ReviewGUI} class represents a graphical panel component for displaying the {@link Review} object.
 * <p>
 * This class is part of the GUI layer of the {@link PreviewRestaurantGUI} and is typically used to have a graphical interface of the review itself.
 * </p>
 * 
 * @author Damiano De Mutiis    761348 (CO)
 * @author Matteo Porto Bonacci 761396 (CO)
 * @author Matteo Monticone     761701 (CO)
 * @author Mattia Tamburo       761743 (CO)
 */
public final class ReviewGUI extends javax.swing.JPanel {

    //<editor-fold defaultstate="collapsed" desc="Constructor">
    /**
     * Creates a new {@code ReviewGUI} panel and initializes its components.
     * <p>
     * This constructor also sets the review to insert the data needed to have a graphical interface of the review itself.
     * </p>
     *
     * @param controller the {@link Controller} class that manages the screen layout
     * @param review the {@link Review} class that represents the review
     * @param bg the {@code Color} of the background for the {@code ReviewGUI}
     */
    public ReviewGUI(Controller controller, Review review, Color bg) {
        initComponents();
        this.controller = controller;
        this.review     = review;
        this.bg         = bg;
        initGUI();
    }
    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc="Initialization">
    /**
     * Initializes the graphical user interface (GUI) for the {@code PreviewReviewGUI} page.
     */
    private void initGUI() {
        initFields();
        initPreviewReviewGUI();
        initEvents();
    }
    
    /**
     * Initializes the basic fields of the {@code PreviewReviewGUI} panel.
     */
    private void initFields() 
    {
        pnl_usernameRatingReview = new JPanel(new BorderLayout());
        lbl_usernameReview       = new JLabel(review.getUsername());
        lbl_rating               = new JLabel(String.valueOf(review.getRating()));
        txt_reviewContent        = new JTextArea(review.getContent());
        lbls                     = new JLabel[] {
            lbl_usernameReview,
            lbl_rating
        };
    }
    
    /**
     * Initializes the layout and appearance of the home page.
     */
    private void initPreviewReviewGUI() 
    {
        this.setBackground(bg);
        this.setLayout(new BorderLayout());
        this.setPreferredSize(new Dimension(0, REVIEW_HEIGHT));
        
        pnl_usernameRatingReview.setBackground(bg);
        pnl_usernameRatingReview.setBorder(BORDER_NORTH_PNL);
        pnl_usernameRatingReview.setPreferredSize(new Dimension(0, NORTH_CONTENT_HEIGHT));
        
        for (JLabel lbl : lbls) {
            lbl.setBackground(bg);
            lbl.setForeground(FG_DEFAULT);
            lbl.setHorizontalAlignment  (JLabel.LEFT);
            lbl.setVerticalAlignment    (JLabel.CENTER);
            lbl.setFont                 (this.getFont());
            lbl.setBorder               (PADDING_LBL);
            lbl.setOpaque               (true);
        }
        lbl_rating.setHorizontalAlignment(JLabel.RIGHT);
        
        txt_reviewContent.setBackground   (bg);
        txt_reviewContent.setBorder       (PADDING_TXT);
        txt_reviewContent.setLineWrap     (true);
        txt_reviewContent.setWrapStyleWord(true);
        txt_reviewContent.setEditable     (false);
        txt_reviewContent.setFocusable    (false);
        
    }
    
    /**
     * Sets up event listeners for user interaction.
     */
    private void initEvents() 
    {
        
    }
    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc="Event Listeners">
    //</editor-fold>

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    //<editor-fold defaultstate="collapsed" desc="Consts">
    private final Color              FG_DEFAULT           = Color.BLACK;
    private final Border             PADDING_LBL          = BorderFactory.createEmptyBorder(5, 5, 5, 5);
    private final Border             PADDING_TXT          = BorderFactory.createEmptyBorder(3, 3, 3, 3);
    private final Border             BORDER_NORTH_PNL     = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.BLACK);
    private final int                NORTH_CONTENT_HEIGHT = 30;
    private final int                REVIEW_HEIGHT        = 100;
    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc="Components">
    private JPanel    pnl_usernameRatingReview;
    private JLabel    lbl_usernameReview;
    private JLabel    lbl_rating;
    private JTextArea txt_reviewContent;
    private JLabel[]  lbls;
    private JLabel    btn_addReview;
    private JLabel    btn_back;
    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc="Fields">
    private final Controller controller;
    private final Color      bg;
    private final Review     review;
    //</editor-fold>

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
