package theknife.gui;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.BorderFactory;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 * @author Matteo Monticone     761701 (CO)
 * @author Damiano De Mutiis    ------ (CO)
 * @author Matteo Porto Bonacci ------ (CO)
 * @author Mattia Tamburo       ------ (CO)
 */

public class Upperbar extends javax.swing.JPanel {

    /**
     * Creates new form Upperbar
     */
    public Upperbar() {
        initComponents();
        initGUI();
    }
    
    private void initGUI() {
        initFields();
        initUpperbar();
    }
    
    private void initFields() {
        pnls_upperbar = new JPanel[3]; //0 = west; 1 = center; 2 = east;
        this.setLayout(new BorderLayout());
        txt_searchbar = new JTextField();
    }
    
    private void initUpperbar() {
        for (int i = 0; i < pnls_upperbar.length; i++) {
            pnls_upperbar[i] = new JPanel(new BorderLayout());
            pnls_upperbar[i].setPreferredSize(new Dimension(SIDEBUTTONS_WIDTH, this.getPreferredSize().height));
        }
        pnls_upperbar[0].setBackground(Color.BLUE);
        pnls_upperbar[1].setBackground(Color.CYAN);
        pnls_upperbar[1].setBorder(BorderFactory.createEmptyBorder(20, 50, 20, 50));
        pnls_upperbar[1].add(txt_searchbar, BorderLayout.CENTER);
        pnls_upperbar[2].setBackground(Color.GRAY);
        this.add(pnls_upperbar[0], BorderLayout.WEST);
        this.add(pnls_upperbar[1], BorderLayout.CENTER);
        this.add(pnls_upperbar[2], BorderLayout.EAST);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(0, 255, 51));
        setMinimumSize(new java.awt.Dimension(854, 80));
        setPreferredSize(new java.awt.Dimension(854, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 854, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private final int SIDEBUTTONS_WIDTH = 100;
    
    //<editor-fold defaultstate="collapsed" desc="Fields">
    private JPanel[] pnls_upperbar;
    private JTextField txt_searchbar;
    //</editor-fold>

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
